version: '3.8'

services:
  auth:
    build: ../backend/auth
    container_name: auth
    env_file:
      - ../backend/auth/.env
    networks:
      - backend_net
      - db_net

  messaging:
    build: ../backend/messaging
    container_name: messaging
    env_file:
      - ../backend/messaging/.env
    networks:
      - backend_net
      - db_net

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/site.conf:/etc/nginx/conf.d/site.conf
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - auth
      - messaging
    networks:
      - backend_net

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 6h & wait $${!}; certbot renew; done'"
    networks:
      - backend_net

networks:
  backend_net:
  db_net:
    external: true
