version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: messaging_app
      POSTGRES_PASSWORD: secure_db_password
      POSTGRES_DB: messaging_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres/initdb:/docker-entrypoint-initdb.d
      - ./postgres/pg_hba.conf:/etc/postgresql/pg_hba.conf
    networks:
      - db_net

  redis:
    image: redis:7
    container_name: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - redisdata:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - db_net

volumes:
  pgdata:
  redisdata:

networks:
  db_net:
    name: db_net
